### ISSUE TITLE
gulp build command is error

### ISSUE THREAD

**Issue by joonseolee** [devslaw/TypeScript-Node.js-REST-example#4]
I followed your words like installing npm, gulp, nodemon ...
and when I enter the command `gulp build`, it spits an error 
how can I fix it?

I think it is an error about gulp version?? am I right?
```
$ gulp build
[16:51:59] Working directory changed to D:\repository\vscode\TypeScript-Node.js-REST-example
assert.js:339
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (D:\repository\vscode-repository\TypeScript-Node.js-REST-example\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (D:\repository\vscode-repository\TypeScript-Node.js-REST-example\node_modules\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (D:\repository\vscode-repository\TypeScript-Node.js-REST-example\gulpfile.js:8:6)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)

```

**Comment by tdsang01** [comment]
Same error!
